[config]
skip_core_tasks = true

[tasks.default]
alias = "run"

[tasks.format]
description = "cargo format"
command = "cargo"
args = ["fmt"]

[tasks.check]
description = "cargo check"
command = "cargo"
args = ["check"]

[tasks.build]
description = "cargo build"
command = "cargo"
args = ["build"]

[tasks.run]
description = "cargo run"
command = "cargo"
args = ["run"]

[tasks.clippy]
description = "cargo clippy"
command = "cargo"
args = ["clippy"]

[tasks.clean]
description = "cargo clean"
command = "cargo"
args = ["clean"]
